I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    Narator "You're name is Emily!"
Exception: Sayer 'Narator' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    Narator "You're name is Emily!"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Narator' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Story Of A Girl Beta Test 1 1.0
Fri Jun 24 15:05:24 2022
